services:
    storage:
        image: redis:latest
        networks:
            - app-network
    counter:
        build: ./counter
        ports:
            - 80:3000
        environment:
            - PORT=3000
            - STORAGE_URL=redis://storage
        networks:
            - app-network
    library:
        build: ./main
        volumes:
            - ./main/load:/app/load
        ports:
            - 81:3000
        environment:
            - PORT=3000
            - COUNTER_URL=http://counter:3000
        networks:
            - app-network
networks:
    app-network:
        driver: bridge